version: "3.7"
services:
  app:
    container_name: llsolar-app
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/etc/php/conf.d/local.ini
    networks:
      - lahmi

  mysql:
    container_name: llsolar-mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
        - "3388:3306"
    networks:
        - lahmi

  nginx:
    container_name: llsolar-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - mysql
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lahmi

networks:
  lahmi:
    driver: bridge

volumes:
  dbdata:
    driver: local

